In [3]:
import numpy as np

In [ ]:
x=np.random.rand(10000)
y=np.random.rand(10000)

In [ ]:
def length(x,y):
  array=[]
  for i in range(10000):
    length0 = np.sqrt(x[i]*x[i]+y[i]*y[i]) 
    if length0<1:
      array.append(length0)

  return array

In [ ]:
aray=np.array(length(x,y))

In [ ]:
1-aray.size/10000

0.21930000000000005

###better method


In [ ]:
sample = np.random.rand(10000,2)

In [ ]:
sq_sample=sample*sample
dffo=np.sqrt(np.sum(sq_sample,axis=1))

In [ ]:
ouside_points=np.sum(dffo>1)

In [ ]:
ouside_points/10000

0.2182

more fast


In [ ]:
outside_points=np.sum(np.sqrt(np.sum(sample*sample,axis=1))>1)

###FILE HANDLING

In [ ]:
planet_small = np.loadtxt("planet_small.txt",
                          skiprows=1,
                          usecols=(1,2,3,4,5,6,7,8,9)
                          )

In [ ]:
planet_small

array([[3.3000e-01, 4.8700e+00, 5.9700e+00, 6.4200e-01, 1.8980e+03,
        5.6800e+02, 8.6800e+01, 1.0200e+02, 1.4600e-02],
       [5.7900e+01, 1.0820e+02, 1.4960e+02, 2.2790e+02, 7.7860e+02,
        1.4335e+03, 2.8725e+03, 4.4951e+03, 5.9064e+03],
       [4.2226e+03, 2.8020e+03, 2.4000e+01, 2.4700e+01, 9.9000e+00,
        1.0700e+01, 1.7200e+01, 1.6100e+01, 1.5330e+02]])

In [6]:
planet= np.genfromtxt("planet.txt",
                       skip_header = 1,
                       usecols=[1,2,3,4,5,6,7,8,9]
                       )

In [7]:
planet

array([[ 3.30000e-01,  4.87000e+00,  5.97000e+00,  7.30000e-02,
         6.42000e-01,  1.89800e+03,  5.68000e+02,  8.68000e+01,
         1.02000e+02],
       [ 4.87900e+03,  1.21040e+04,  1.27560e+04,  3.47500e+03,
         6.79200e+03,  1.42984e+05,  1.20536e+05,  5.11180e+04,
         4.95280e+04],
       [ 5.42700e+03,  5.24300e+03,  5.51400e+03,  3.34000e+03,
         3.93300e+03,  1.32600e+03,  6.87000e+02,  1.27100e+03,
         1.63800e+03],
       [ 3.70000e+00,  8.90000e+00,  9.80000e+00,  1.60000e+00,
         3.70000e+00,  2.31000e+01,  9.00000e+00,  8.70000e+00,
         1.10000e+01],
       [ 4.30000e+00,  1.04000e+01,  1.12000e+01,  2.40000e+00,
         5.00000e+00,  5.95000e+01,  3.55000e+01,  2.13000e+01,
         2.35000e+01],
       [ 1.40760e+03, -5.83250e+03,  2.39000e+01,  6.55700e+02,
         2.46000e+01,  9.90000e+00,  1.07000e+01, -1.72000e+01,
         1.61000e+01],
       [ 4.22260e+03,  2.80200e+03,  2.40000e+01,  7.08700e+02,
         2.47000e+01,  9.90000

In [8]:
planet.shape

(20, 9)

In [9]:
np.isnan(planet  )

array([[False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, 

###case study and problem 

In [11]:
!head cric_data.tsv

	Sachin Tendulkar	Rahul Dravid	India
0	100	78	342
1	11	62	191
2	8	85	252
3	71	24	307
4	104	17	229
5	18	104	246
6	8	76	226
7	86	74	288
8	12	60	216


In [12]:
data  = np.genfromtxt("cric_data.tsv",skip_header=1,usecols=[1,2,3])

In [13]:
all_mean = np.mean(data,axis=0)

In [14]:
all_mean

array([ 39.87555556,  32.06222222, 220.79555556])

In [15]:
all_meadian = np.median(data,axis=0)

In [16]:
all_meadian

array([ 27.,  22., 216.])

In [18]:
all_iqr = np.percentile(data,75,axis=0)-np.percentile(data,25,axis=0)
all_iqr

array([57., 46., 98.])

In [32]:
sachin = data[:,0]
print(sachin.shape)
rahul=data[:,1]
rahul.shape

(225,)


(225,)

In [47]:
new_sach=sachin.reshape(9,25)
np.mean(new_sach,axis=1)

array([33.96, 49.4 , 38.48, 40.16, 39.36, 38.2 , 44.6 , 39.52, 35.2 ])

In [24]:
np.histogram(sachin)

(array([99, 36, 28, 16, 11, 17,  8,  8,  1,  1]),
 array([  0. ,  18.6,  37.2,  55.8,  74.4,  93. , 111.6, 130.2, 148.8,
        167.4, 186. ]))

In [48]:
sachin_century=sachin[sachin>100]

In [49]:
np.mean(sachin_century)

128.2608695652174

In [27]:
sachin_rahul = data[:,0:2]
sachin_rahul.shape

(225, 2)

In [34]:
s_score=sachin[rahul<10]

np.mean(s_score)

40.74285714285714

In [ ]:
def max_val(arr):
  if arr[0]>arr[1]:
    return "sachin" 
  elif arr[1]>arr[0]:
    return "rahul"  
  else:
    return 0 
result=[]
for item in sachin_rahul:
  result.append(max_val(item))

result


In [51]:
sorted_india = data[:,2].argsort()

In [70]:
qrs = np.percentile(data[:,2],[25,50,75,100])


In [66]:
np.mean(sachin[data[:,2]<])

39.799107142857146

In [73]:
india = data[:,2]
qrs = qrs.reshape(4,1)
indices = india<qrs
for i in range(4):
  print(i,np.mean(sachin[indices[i]]))

0 19.672727272727272
1 28.18018018018018
2 31.688622754491018
3 39.799107142857146


In [74]:
is_rahul_higher = np.argmax(sachin_rahul,axis=1)


In [ ]:
np.where(is_rahul_higher==0,'sachin','Rahul')

In [90]:
np.mean(sachin[sachin>40])

x_arr = np.arange(0,101,5)
x_arr= x_arr.reshape(x_arr.shape[0],1)
x_arr.shape

(21, 1)

In [92]:
indices=(sachin>=x_arr)
indices.shape

(21, 225)

In [94]:
for i in range(x_arr.shape[0]):
  print(x_arr[i,0] ,np.mean(sachin[indices[i,:]])-x_arr[i,0])

0 39.87555555555556
5 45.61363636363637
10 47.48026315789474
15 47.45255474452555
20 46.824
25 44.10084033613445
30 45.13461538461539
35 43.24742268041237
40 44.05882352941177
45 43.41558441558442
50 43.98529411764706
55 42.317460317460316
60 38.67213114754098
65 37.654545454545456
70 37.08163265306122
75 34.347826086956516
80 30.75
85 28.650000000000006
90 27.400000000000006
95 26.433333333333337
100 25.0


In [100]:
cumu_sum=np.cumsum(sachin)
np.histogram(cumu_sum,bins=np.arange(0,10000,1000))

(array([29, 18, 26, 25, 26, 26, 23, 22, 30]),
 array([   0, 1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000]))